// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package models

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int32 `json:"code" xml:"code"`

	// Message Error message
	Message string `json:"message" xml:"message"`
}

// NewPet defines model for NewPet.
type NewPet struct {
	// Name Name of the pet
	Name string `json:"name" xml:"name"`

	// Tag Type of the pet
	Tag *string `json:"tag,omitempty" xml:"tag"`
}

// Pet defines model for Pet.
type Pet struct {
	// Id Unique id of the pet
	Id int64 `json:"id" xml:"id"`

	// Name Name of the pet
	Name string `json:"name" xml:"name"`

	// Tag Type of the pet
	Tag *string `json:"tag,omitempty" xml:"tag"`
}

// FindPetsParams defines parameters for FindPets.
type FindPetsParams struct {
	// Tags tags to filter by
	Tags *[]string `form:"tags,omitempty" json:"tags,omitempty" xml:"tags"`

	// Limit maximum number of results to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty" xml:"limit"`
}

// AddPetJSONRequestBody defines body for AddPet for application/json ContentType.
type AddPetJSONRequestBody = NewPet
