// Package xgojsonignore provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package xgojsonignore

// Client defines model for Client.
type Client struct {
	ComplexField *struct {
		AccountName *string `json:"accountName,omitempty" xml:"accountName"`
		Name        *string `json:"name,omitempty" xml:"name"`
	} `json:"complexField,omitempty" xml:"complexField"`
	Name string `json:"name" xml:"name"`
}

// ClientWithExtension defines model for ClientWithExtension.
type ClientWithExtension struct {
	ComplexField *struct {
		AccountName *string `json:"accountName,omitempty" xml:"accountName"`
		Name        *string `json:"name,omitempty" xml:"name"`
	} `json:"-" xml:"complexField"`
	Name string `json:"name" xml:"name"`
}
